Introduce Omni lock into Godwoken and rm clerkb (POA)
RetricSu/godwoken-kicker pull request #172
Opened 2022-03-06 02:37 UTC by Flouse

- replace https://github.com/RetricSu/godwoken-kicker/pull/171
- omni_lock has been added into ghcr.io/flouse/godwoken-prebuilds:v1.0.x-omni-lock-202203051513
  see: https://github.com/Flouse/godwoken-docker-prebuilds/blob/v1.0.x-omni-lock/Makefile#L13
- test Kicker while sending PR to compatibility-changes branch
   https://github.com/RetricSu/godwoken-kicker/compare/compatibility-changes...omni-lock#diff-487ff6372ad077cb90406a903f435752a206d27afd9553d9ba1212412410708fR7

2022-03-06 06:29 UTC, RetricSu commented on Makefile
> +rebuild-scripts: rebuild-gw-scripts-and-bin rebuild-polyjuice-bin
```suggestion
rebuild-scripts: rebuild-gw-scripts-and-bin rebuild-polyjuice-bin rebuild-omni-lock
```

2022-03-06 06:31 UTC, RetricSu commented on docker/.build.mode.env
>  MANUAL_BUILD_CLERKB=false
```suggestion
```
remove this poa env?

2022-03-06 06:33 UTC, RetricSu commented on .gitignore
>  !config/scripts/release/state
```suggestion
```

2022-03-06 06:34 UTC, RetricSu commented on .gitignore
>  !config/scripts/release/state
state is also poa, can be removed too

2022-03-06 08:50 UTC, keroro520 requested changes

2022-03-06 08:50 UTC, keroro520 commented on docker/.build.mode.env
>  CLERKB_GIT_CHECKOUT=v0.4.0
clerkb configurations should be removed now

2022-03-06 08:50 UTC, keroro520 commented on docker/layer2/entrypoint.sh
> +$GW_TOOLS_BIN deploy-genesis --ckb-rpc ${CKB_RPC} --scripts-deployment-path deploy/scripts-deploy-result.json -r deploy/rollup-config.json --omni-lock-config-path deploy/scripts-deploy-result.json -o
`--omni-lock-config-path deploy/scripts-deploy-result.json` ? Not omni config?

2022-03-06 09:24 UTC, Flouse commented on docker/layer2/entrypoint.sh
> +$GW_TOOLS_BIN deploy-genesis --ckb-rpc ${CKB_RPC} --scripts-deployment-path deploy/scripts-deploy-result.json -r deploy/rollup-config.json --omni-lock-config-path deploy/scripts-deploy-result.json -o
The omni config supposed to be in `deploy/scripts-deploy-result.json`.

see: https://github.com/RetricSu/godwoken-kicker/pull/172/files#diff-6f62da3aed030fbfd698e10fde099189b986aeb385d34a3ffac8365408a480feR19

2022-03-06 10:34 UTC, Flouse commented
## Test `make start` passed in CI
https://github.com/RetricSu/godwoken-kicker/runs/5437886319?check_suite_focus=true#step:4:644

@RetricSu @keroro520 @zeroqn 
Please review again, thx.

2022-03-06 11:31 UTC, keroro520 commented on docker/layer2/entrypoint.sh
> +$GW_TOOLS_BIN deploy-genesis --ckb-rpc ${CKB_RPC} --scripts-deployment-path deploy/scripts-deploy-result.json -r deploy/rollup-config.json --omni-lock-config-path deploy/scripts-deploy-result.json -o
I am not sure. I just notice that the Rust definition [`OmniLockConfig`](https://github.com/zeroqn/godwoken/blob/c18807b5cfaa961c230e15e3a381570c324db6f8/crates/tools/src/types.rs#L70-L74) is not a `Script`.

2022-03-06 11:36 UTC, keroro520 commented on docker/layer2/entrypoint.sh
> +$GW_TOOLS_BIN deploy-genesis --ckb-rpc ${CKB_RPC} --scripts-deployment-path deploy/scripts-deploy-result.json -r deploy/rollup-config.json --omni-lock-config-path deploy/scripts-deploy-result.json -o
@zeroqn Could you confirm it?

2022-03-07 02:50 UTC, merged

2022-03-07 03:09 UTC, zeroqn commented on docker/layer2/entrypoint.sh
> +$GW_TOOLS_BIN deploy-genesis --ckb-rpc ${CKB_RPC} --scripts-deployment-path deploy/scripts-deploy-result.json -r deploy/rollup-config.json --omni-lock-config-path deploy/scripts-deploy-result.json -o
Yes