feat: refactor setup
RetricSu/godwoken-kicker pull request #180
Opened 2022-03-10 12:02 UTC by keroro520

2022-03-11 07:01 UTC, Flouse requested changes

2022-03-11 10:42 UTC, keroro520 commented on docker/layer2/setup-godwoken.sh
> +    RUST_BACKTRACE=full gw-tools create-creator-account \
done

2022-03-12 15:56 UTC, Flouse commented
- [ ] Please check the `make clean` command and make sure it works correctly

2022-03-13 09:35 UTC, keroro520 commented
> * [x]  Please check the `make clean` command and make sure it works correctly

Done.
The new commit 907045d6cb819421ed0e5e8830035148e535636f adds support for `make clean`, `make clean-cache` and `clean-workspace`.

2022-03-14 07:45 UTC, Flouse approved these changes

2022-03-14 09:13 UTC, Flouse requested changes

2022-03-14 09:13 UTC, Flouse commented on docker/docker-compose.yml
> +      GODWOKEN_MODE: fullnode
```suggestion
      RUST_LOG: info,gw_generator=debug
      GODWOKEN_MODE: fullnode
```

2022-03-14 09:13 UTC, Flouse commented on docker/docker-compose.yml
> +      GODWOKEN_MODE: fullnode
`gw_generator=debug` make us be able to watch Polyjuice logs.

2022-03-14 09:30 UTC, Flouse approved these changes

2022-03-14 09:38 UTC, RetricSu commented on docker/docker-compose.yml
> +    image: ghcr.io/flouse/godwoken-prebuilds:v1.0.x-202203101259
there are 4 repeated lines of this image name `ghcr.io/flouse/godwoken-prebuilds:v1.0.x-202203101259`, if want to change it to different one, have to change 4 places, seems a little inconvenient

2022-03-14 14:08 UTC, keroro520 commented on docker/docker-compose.yml
> +    image: ghcr.io/flouse/godwoken-prebuilds:v1.0.x-202203101259
I see what you mean. The "check-godwoken-started-successfully" and "check-godwoken-started-successfully" services are workarounds to the service health checks, they simply use the `curl` command. There is no problem using a generic Docker image for these two services.

While "setup-godwoken" and "godwoken" must use the same docker image. I think it's fine. What do you think?

2022-03-15 01:44 UTC, RetricSu commented on docker/docker-compose.yml
> +    image: ghcr.io/flouse/godwoken-prebuilds:v1.0.x-202203101259
right now we can use this method. later when we have more time, we can think about keeping it at one place like extracting value to some default env variables, but if user provide their own env variables, it can still work as they expected.

2022-03-15 01:51 UTC, RetricSu approved these changes

2022-03-15 04:18 UTC, keroro520 commented on docker/docker-compose.yml
> +    image: ghcr.io/flouse/godwoken-prebuilds:v1.0.x-202203101259
Will change later.

2022-03-15 04:18 UTC, merged

2022-03-24 05:54 UTC, keroro520 commented on docker/docker-compose.yml
> +    image: ghcr.io/flouse/godwoken-prebuilds:v1.0.x-202203101259
https://github.com/RetricSu/godwoken-kicker/pull/204 takes over this update. cc @RetricSu