Specific accounts for specific purpose
RetricSu/godwoken-kicker pull request #200
Opened 2022-03-22 10:04 UTC by keroro520

2022-03-22 11:10 UTC, Flouse requested changes

2022-03-22 11:10 UTC, Flouse commented on docs/accounts.md
> +  This key must be the same as [Polyjuice root account](./accounts.md#polyjuice-root-account). I have no idea why.
```suggestion
  This key belongs to [EthEoaMappingRegister.wallet](https://github.com/nervosnetwork/godwoken/blob/3605c70/crates/eoa-mapping/src/eth_register.rs#L22). It must be related to a created Godwoken Account. It will be used to [sign](https://github.com/nervosnetwork/godwoken/blob/3605c70/crates/eoa-mapping/src/eth_register.rs#L147) EthEoaMappingRegister transaction which is a layer2 transaction.
```

2022-03-22 11:11 UTC, Flouse requested changes

2022-03-22 11:11 UTC, Flouse commented on docs/accounts.md
> +  `gw-tools deploy-scripts` uses this account to deploy rollup-related scripts to layer1.
```suggestion
```

2022-03-22 11:12 UTC, Flouse commented on docs/accounts.md
> +  `gw-tools deploy-scripts` uses this account to deploy rollup-related scripts to layer1.
Duplicate line

2022-03-24 02:58 UTC, RetricSu approved these changes

2022-03-24 08:17 UTC, merged