fix(kicker): run cargo check in user environment
RetricSu/godwoken-kicker pull request #206
Opened 2022-03-24 09:44 UTC by zeroqn

2022-03-24 10:19 UTC, keroro520 requested changes

2022-03-24 10:19 UTC, keroro520 commented on kicker
> +            retricsu/godwoken-manual-build:ckb2021 cargo check --locked
Just remove `cargo check`, L304-L312.

`cargo check` is used to download dependencies from the host machine. Running it inside a Docker container defeats its purpose. Therefore, just remove it.

2022-03-24 11:15 UTC, zeroqn commented on kicker
> +            retricsu/godwoken-manual-build:ckb2021 cargo check --locked
Ok

2022-03-25 02:50 UTC, keroro520 approved these changes

2022-03-25 02:50 UTC, keroro520 commented on kicker
> +            retricsu/godwoken-manual-build:ckb2021 cargo build --locked --release
Please adapt the code comments L304-305

2022-03-25 07:00 UTC, zeroqn commented on kicker
> +            retricsu/godwoken-manual-build:ckb2021 cargo build --locked --release
Add rustfmt.

2022-03-25 07:46 UTC, RetricSu approved these changes

2022-03-25 07:48 UTC, merged