feat: Using web3 migrations
RetricSu/godwoken-kicker pull request #253
Opened 2022-05-18 10:20 UTC by classicalliu

Related PR:
- https://github.com/nervosnetwork/godwoken-web3/pull/346

2022-05-20 07:58 UTC, Flouse approved these changes

2022-05-20 09:40 UTC, keroro520 requested changes

2022-05-20 09:40 UTC, keroro520 commented on docker/docker-compose.yml
> +    entrypoint: /var/lib/web3/migrations_entrypoint.sh
Would it be possible that do the migration job inside [`web3/entrypoint.sh`](https://github.com/RetricSu/godwoken-kicker/blob/compatibility-changes/docker/web3/entrypoint.sh).

2022-05-20 09:43 UTC, keroro520 commented on docker/docker-compose.yml
> +    entrypoint: /var/lib/web3/migrations_entrypoint.sh
```
cd /godwoken-web3

// Question: Should we check whether the migration job should start?
yarn knex migrate:latest

yarn run start
```

2022-05-20 10:40 UTC, classicalliu commented on docker/docker-compose.yml
> +    entrypoint: /var/lib/web3/migrations_entrypoint.sh
web3-indexer also need to start after migrations completed, how web3-indexer get the status or start web3-indexer after web3 server already started ?

2022-05-20 11:06 UTC, keroro520 commented on docker/docker-compose.yml
> +    entrypoint: /var/lib/web3/migrations_entrypoint.sh
webs-indexer will wait until web3 becomes healthy:
https://github.com/RetricSu/godwoken-kicker/blob/0880fdf244daf9bacb8617cc8d4e0fce630ce1e6/docker/docker-compose.yml#L155-L157

2022-05-23 03:44 UTC, classicalliu commented on docker/docker-compose.yml
> +    entrypoint: /var/lib/web3/migrations_entrypoint.sh
ok, I see

2022-05-23 05:02 UTC, keroro520 approved these changes

2022-05-23 05:03 UTC, merged