feat: new article on "running godwoken-kicker on Windows11"
RetricSu/godwoken-kicker pull request #277
Opened 2022-06-14 02:43 UTC by ShookLyngs

2022-06-14 02:51 UTC, Flouse approved these changes

2022-06-15 02:33 UTC, keroro520 requested changes

2022-06-15 02:33 UTC, keroro520 commented on docs/kicker-start-on-windows-11.md
> +- WSL 2 OS - Ubuntu 22.04 LTS
It would be very helpful for some Windows users that note Godwoken-Kicker can not run on the Windows systems and why.

// As this note is so important, I mark this message as a request change.

2022-06-15 02:33 UTC, keroro520 commented on docs/kicker-start-on-windows-11.md
> +- You might want to go to Windows Terminal’s setting page, then go to Profiles → Defaults → Advanced, find `Profile termination behavior` and set it to `Never close automatically`, this will prevent
The best practice is "cloning in WSL 2 subsystem", right? If so, I believe introducing this only would be sufficient.

"Clone Godwoken-Kicker in Windows’ File System" is Windows-domain knowledge, or rather, personal knowledge. I suggest removing this part or moving it to the end of this document as a part of "known issues".

2022-06-15 02:33 UTC, keroro520 commented on docs/kicker-start-on-windows-11.md
> +    [Sharing SSH keys between Windows and WSL 2](https://devblogs.microsoft.com/commandline/sharing-ssh-keys-between-windows-and-wsl-2/)
Usually, as this is an open-source repo, we recommend users clone via HTTPS, without SSH key or password required.

2022-06-15 02:33 UTC, keroro520 commented on docs/kicker-start-on-windows-11.md
> +3. Go into projects folder, and then clone the kicker tool into the folder
Missed the important part: `git clone https://github.com/RetricSu/godwoken-kicker`.

2022-06-15 03:48 UTC, Flouse commented on docs/kicker-start-on-windows-11.md
> +- You might want to go to Windows Terminal’s setting page, then go to Profiles → Defaults → Advanced, find `Profile termination behavior` and set it to `Never close automatically`, this will prevent
suggest removing this part too.

The best practice with one choice is better for this case.

2022-06-16 02:55 UTC, ShookLyngs commented
@keroro520 The article is updated:
1. Added a section about why windows-based developer might need the article
2. Deleted section about working on Windows' File System
3. Deleted section about setting a SSH key

2022-06-16 02:58 UTC, keroro520 approved these changes

2022-06-16 02:59 UTC, merged